### ISSUE TITLE
TypeError: Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by eighthave** [freeseek/getmyancestors#15]
Thanks for this tool!  I'm trying to download my tree and it runs for a while and downloads maybe 100 or more JSON files, then crashes with:

```console
$ ./getmyancestors.py -a 7 -m -o /home/hans/Downloads/familysearch.gedcom -v
...snip...
[2018-01-01 12:43:21]: Downloading: https://familysearch.org/platform/tree/couple-relationships/MZYH-F8B/notes.json
[2018-01-01 12:43:23]: Status code: 204
[2018-01-01 12:43:23]: Status code: 204
[2018-01-01 12:43:23]: Status code: 204
[2018-01-01 12:43:23]: Status code: 204
[2018-01-01 12:43:23]: Status code: 204
Traceback (most recent call last):
  File "./getmyancestors.py", line 943, in <module>
    tree.print(args.o)
  File "./getmyancestors.py", line 827, in print
    self.indi[fid].print(file)
  File "./getmyancestors.py", line 608, in print
    file.write('1 _MILT ' + o.value + '\n')
TypeError: Can't convert 'NoneType' object to str implicitly

```

**Comment by eighthave** [comment]
This seems to be fixed by #13
